prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from rest_framework import viewsets
from rest_framework import permissions

from provito.serializers import *
from provito.models import *



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('provito.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

provito/urls.py
from django.urls import path
from rest_framework import routers
from provito import views
from .views import BoardList, BoardCreate, BoardUpdate, BoardDetail, BoardAuthorList, BoardCategoryList, accept, delete



from django.urls import path, include


router = routers.DefaultRouter()
router.register(r'schools', views.BoardViewset)
router.register(r'classes', views.CategoryViewset)
router.register(r'students', views.CommentViewest)

urlpatterns = [
    path('', BoardList.as_view(), name='boardlist'),
    path('create/', BoardCreate.as_view(), name='create'),
    path('<int:pk>/', BoardDetail.as_view(), name='detail'),
    path('edit/<int:pk>/', BoardUpdate.as_view(), name='edit'),
    path('myboard/<int:pk>/', BoardAuthorList.as_view(), name='myboard'),
    path('accept/<int:pk>/', accept, name='accept'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('category/<int:pk>/', BoardCategoryList.as_view(), name='category'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))


]

provito/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField


class Board(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_create = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, blank=True)
    title = models.CharField(max_length=64)
    content = RichTextUploadingField(blank=True, null=True)

    def __str__(self):
        return f'{self.title}'


class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.name}'


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    board = models.ForeignKey('Board', on_delete=models.CASCADE)
    text = models.CharField(max_length=256)
    date_create = models.DateTimeField(auto_now_add=True)

    sent_for_approval = 'sent for approval'
    accepted = 'accepted'
    choice = (
        ('sent for approval', 'Отправлено на согласование'),
        ('accepted', 'Согласовано')
    )
    status = models.CharField(choices=choice, default=sent_for_approval, max_length=17)
    deleted = models.BooleanField(default=False)

provito/forms.py
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget

from .models import Board, Comment


class BoardForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Board
        fields = ('category', 'title', 'content',)


class CommentForm(forms.ModelForm):
    text = forms.CharField(label='Комментарий:')

    class Meta:
        model = Comment
        fields = ('text',)

provito/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, Http404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.urls import reverse_lazy
from django.core.mail import send_mail

from .models import Board, Category, Comment
from .forms import BoardForm, CommentForm
from .filters import CommentFilter
from .tasks import send_email


class BoardList(generic.ListView):
    model = Board
    template_name = 'provito/boards.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['board'] = Board.objects.order_by('-date_create')
        context['category'] = Category.objects.all()
        return context


class BoardCategoryList(generic.ListView):
    model = Board
    template_name = 'provito/boards.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['board'] = Board.objects.all().filter(category_id=self.kwargs.get('pk')).order_by('-date_create')
        context['category'] = Category.objects.all()
        return context


class BoardDetail(generic.DetailView):
    model = Board

    def get(self, request, *args, **kwargs):
        commentform = CommentForm()
        board = Board.objects.get(id=kwargs.get('pk'))
        comment = Comment.objects.filter(board_id=kwargs.get('pk'))
        return render(request,
                      'provito/board_detail.html',
                      {'commentform': commentform,
                       'board': board,
                       'comment': comment})

    def post(self, request, *args, **kwargs):
        commentform = CommentForm(request.POST)
        if commentform.is_valid():
            data = commentform.cleaned_data
            user = User.objects.get(id=request.user.id)
            Comment.objects.create(author=user,
                                   board=Board.objects.get(id=kwargs.get('pk')),
                                   text=data['text'])
            return redirect(f"/{kwargs.get('pk')}/")
        raise Http404('Неверные данные')


class BoardCreate(LoginRequiredMixin, generic.CreateView):
    model = Board
    fields = ('category', 'title', 'content')
    template_name = 'provito/create.html'
    from_class = BoardForm
    success_url = reverse_lazy('boardlist')

    def form_valid(self, form):
        form.instance.author = User.objects.get(id=self.request.user.id)
        return super(BoardCreate, self).form_valid(form)


class BoardUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Board
    template_name = 'provito/edit.html'
    form_class = BoardForm
    success_url = reverse_lazy('boardlist')


class BoardAuthorList(UserPassesTestMixin, generic.ListView):
    queryset = Comment.objects.all()
    template_name = 'provito/comment.html'
    context_object_name = 'comment'

    def test_func(self):
        return self.request.user.id == self.kwargs.get('pk')

    def get_queryset(self):
        self.queryset = self.queryset.filter(board_id__author=self.request.user.id).exclude(deleted=True)
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = CommentFilter(self.request.GET, queryset=self.get_queryset())
        context['board'] = Board.objects.all().filter(author_id=7)
        return context


def accept(request, *args, **kwargs):
    comment = Comment.objects.get(id=kwargs.get('pk'))
    id = comment.board_id
    board = Board.objects.get(id=id)
    if request.user.id == board.author.id:
        comment.status = 'accepted'
        comment.save()
        user = User.objects.get(id=comment.author_id)

        board_author = board.author.username
        comment_text = comment.text
        user_email = user.email

        # Celery and redis are unstable. Made direct sending

        # send_email.apply_async(kwargs={
        #     'board_author': board_author,
        #     'comment_text': comment_text,
        #     'user_email': user_email,
        #                                })

        send_mail(
            subject='Ваш комментарий акцептован',
            message=f'Автор объявления {board_author} акцептовал ваш комментарий "{comment_text}"',
            from_email='alex85aleshka@yandex.ru',
            recipient_list=[user_email],
        )

        return redirect('myboard', pk=request.user.id)
    raise Http404('Вам запрещен доступ на эту страницу')


def delete(request, *args, **kwargs):
    comment = Comment.objects.get(id=kwargs.get('pk'))
    id = comment.board_id
    board = Board.objects.get(id=id)
    if request.user.id == board.author.id:
        comment.deleted = True
        comment.save()
        return redirect('myboard', pk=request.user.id)
    raise Http404('Вам запрещен доступ на эту страницу')


from django.shortcuts import render
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework.response import Response
from provito.serializers import *
from provito.models import *


class BoardViewset(viewsets.ModelViewSet):
   queryset = Board.objects.all()
   serializer_class = BoardSerializer
   def list(self, request, format=None):
       return Response([])


class CategoryViewset(viewsets.ModelViewSet):
   queryset = Category.objects.all()
   serializer_class = CategorySerializer


class CommentViewest(viewsets.ModelViewSet):
   queryset = Comment.objects.all()
   serializer_class = CommentSerializer

templates/provito/board_detail.html
{% extends 'provito/index.html' %}

{% block content %}

<div class="container mt-3">
    <div class="row w-100 mb-3">
        <div class="col-sm-8 mx-auto mb-5">
            <div class="card-header bg-light text-start">
                <div class="row row-cols-3">
                    <div class="col">
                        {{ board.category.name }}
                    </div>
                    <div class="col">
                        {{ board.author }}
                    </div>
                    <div class="col text-end">
                        {{ board.date_create }}
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ board.title }}</h5>
<!--                    <img src="">-->
                    <p>{{ board.content|safe }}</p>
<!--                    <p class="card-text">{{ board.text }}</p>-->
                </div>
            </div>
            <div class="card-footer bg-light text-muted">
                <div class="row">
                    <div class="col-6 text-start">
                        <form method="POST">
                            {% csrf_token %}
                            {{ commentform }}
                            <input type="submit" value="Send">
                        </form>
                    </div>
                    <hr>
                    <div class="container">
                        {% for el in comment %}
                            <div class="row">
                                <div class="col text-start col-md-auto">
                                    {{ el.author.username }} :
                                </div>
                                <div class="col text-start col-md-auto">
                                    {{ el.text }}
                                </div>
                                <div class="col text-end">
                                    {{ el.date_create }}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
<!--                    <div class="col-6 text-end">-->

<!--                    </div>-->
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/provito/boards.html
{% extends "provito/index.html" %}

{% block content %}
<div class="container mt-3">
    <div class="row w-100 mb-3">
        {% for el in board %}
        <div class="col-sm-8 mx-auto mb-5">
            <div class="card-header bg-light text-start">
                <div class="row row-cols-3">
                    <div class="col">
                        {{ el.category.name }}
                    </div>
                    <div class="col">
                        {{ el.author }}
                    </div>
                    <div class="col text-end">
                        {{ el.date_create }}
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ el.title }}</h5>
<!--                    <img src="">-->
                    <p>{{ el.content|safe }}</p>
                    <p class="card-text">{{ el.text }}</p>
                    {% if request.user == el.author %}
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <a href="{% url 'edit' el.id %}" class="btn btn-secondary btn-sm">Edit</a>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="card-footer bg-light text-muted">
                <div class="row">
                    <div class="col-6 text-start">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'detail' el.id %}" class="btn btn-secondary btn-sm">Add comment</a>
                        {% endif %}
                    </div>
<!--                    <div class="col-6 text-end">-->
<!--                        <p>Like</p>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/provito/comment.html
{% extends 'provito/index.html' %}

{% block content %}

<form method="GET" class="text-light">
    {% csrf_token %}
    {{ filter.form }}
    <input type="submit" value="Find">
</form>
{% if filter.qs|length %}
    <div class="container">
        {% for comment in filter.qs %}
            <div class="row">
                <div class="col">
                    <p class="text-light text-start">{{ comment.author }}: {{ comment.text }}</p>
                </div>
                <div class="col-3 text-start">
                    <p class="text-light">{{ comment.get_status_display }}</p>
                </div>
                <div class="col-1">
                    {% if comment.status != 'accepted' %}
                        <a href="{% url 'accept' comment.id %}"><button type="button" class="btn btn-outline-light me-2">Accept</button></a>
                    {% endif %}
                </div>
                <div class="col-1">
                    <a href="{% url 'delete' comment.id %}"><button type="button" class="btn btn-outline-light me-2">Delete</button></a>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <p class="text-light">Ничего не найдено</p>
{% endif %}





{% endblock content %}

templates/provito/create.html
{% extends 'provito/index.html' %}

{% block content %}
<div class="container text-light">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}
        <input type="submit" value="Save">
    </form>
</div>
{% endblock content %}

templates/provito/edit.html
{% extends 'provito/index.html' %}

{% block content %}
<div class="container text-light">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}

        <input type="submit" value="Save">
    </form>
</div>
{% endblock content %}

templates/provito/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/provito/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
      {% load static %}
        {% load custom_filters %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>MMORPG</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body class="text-center bg-dark">


<!--Headers-->
        <header class="p-3 bg-dark text-white fixed-top">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
                    </a>
                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                      <li><a href="/" class="nav-link px-2 text-secondary">MMORPG</a></li>
<!--                      <li><a href="#" class="nav-link px-2 text-white">Features</a></li>-->
<!--                      <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>-->
<!--                      <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>-->
<!--                      <li><a href="#" class="nav-link px-2 text-white">About</a></li>-->
                    </ul>

<!--                    <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">-->
<!--                      <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">-->
<!--                    </form>-->


                    <div class="text-end">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'create' %}"><button type="button" class="btn btn-outline-light me-2">Создать объявление</button></a>
                            <a href="{% url 'myboard' request.user.id %}"><button type="button" class="btn btn-outline-light me-2">Мои объявления</button></a>
                            <a href="/accounts/logout/"><button type="button" class="btn btn-outline-light me-2">Выйти</button></a>
                        {% else %}
                            <a href="/accounts/login/"><button type="button" class="btn btn-outline-light me-2">Вход</button></a>
                        {% endif %}
<!--                      <button type="button" class="btn btn-warning">Sign-up</button>-->
                    </div>
                    <div class="text-center text-light">
                        {{ request.user }}
                    </div>
<!--                    <div class="dropdown text-end border-light">-->
<!--                        <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--                            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">-->
<!--                        </a>-->
<!--                        <ul class="dropdown-menu text-small bg-dark border-light" aria-labelledby="dropdownUser1">-->
<!--                            <li><a class="dropdown-item text-light" href="#">My boards</a></li>-->
<!--&lt;!&ndash;                            <li><a class="dropdown-item" href="#">Settings</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                            <li><a class="dropdown-item text-light" href="">Profile</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                            <li><hr class="dropdown-divider"></li>&ndash;&gt;-->
<!--&lt;!&ndash;                            <li><a class="dropdown-item" href="#">Sign out</a></li>&ndash;&gt;-->
<!--                        </ul>-->
<!--                    </div>-->
                </div>
            </div>
        </header>

<!-- Header-->
        <header class="bg-dark py-3">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-light">
                    <h1 class="display-4 fw-bolder">MMORPG</h1>
                    <p class="lead fw-normal text-white-50 mb-0"></p>
                </div>
            </div>
        </header>

<!--Category section        -->
        <div class="container mx-auto bg-dark">
            <div class="d-grid gap-2 d-md-block mx-auto">
                {% for el in category %}
                    <a href="{% url 'category' el.id %}"><button class="btn btn-secondary" type="button">{{ el.name }}</button></a>
                {% endfor %}
            </div>
        </div>

<!--Card section-->
{% block content%}
{% endblock content %}



        <!-- Footer-->
        <div class="container">
          <footer class="py-3 my-4">
<!--            <ul class="nav justify-content-center border-bottom pb-3 mb-3">-->
<!--              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>-->
<!--              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>-->
<!--              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>-->
<!--              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>-->
<!--              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>-->
<!--            </ul>-->
            <p class="text-center text-muted">Copyright PST Sistema</p>
<!--              <p class="text-center text-muted"></p>-->
<!--              <p class="text-center text-muted">Telegram: </p>-->
<!--              <p class="text-center text-muted">GitHub: </p>-->
          </footer>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>